CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AbilityScoreValues" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Score" integer NOT NULL,
    "Modifier" integer NOT NULL,
    CONSTRAINT "PK_AbilityScoreValues" PRIMARY KEY ("Id")
);

CREATE TABLE "Characters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Class" text NOT NULL,
    "Species" text NOT NULL,
    "CharacterSheetId" integer NOT NULL,
    CONSTRAINT "PK_Characters" PRIMARY KEY ("Id")
);

CREATE TABLE "SavingThrowValues" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Proficient" boolean NOT NULL,
    CONSTRAINT "PK_SavingThrowValues" PRIMARY KEY ("Id")
);

CREATE TABLE "Slots" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Total" integer NOT NULL,
    "Used" integer NOT NULL,
    CONSTRAINT "PK_Slots" PRIMARY KEY ("Id")
);

CREATE TABLE "SpellAttacks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Bonus" integer NOT NULL,
    "Damage" text NOT NULL,
    CONSTRAINT "PK_SpellAttacks" PRIMARY KEY ("Id")
);

CREATE TABLE "SpellSaves" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Ability" text NOT NULL,
    "Dc" integer NOT NULL,
    CONSTRAINT "PK_SpellSaves" PRIMARY KEY ("Id")
);

CREATE TABLE "CharacterSheets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CharacterId" integer NOT NULL,
    "CharacterId1" integer NOT NULL,
    CONSTRAINT "PK_CharacterSheets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CharacterSheets_Characters_CharacterId" FOREIGN KEY ("CharacterId") REFERENCES "Characters" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CharacterSheets_Characters_CharacterId1" FOREIGN KEY ("CharacterId1") REFERENCES "Characters" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ExtractionJobs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "JobToken" text NOT NULL,
    "FileName" text NOT NULL,
    "ContentType" text NOT NULL,
    "FileDataUrl" text NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "StartedAt" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    "ErrorMessage" text,
    "ResultCharacterId" integer,
    CONSTRAINT "PK_ExtractionJobs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExtractionJobs_Characters_ResultCharacterId" FOREIGN KEY ("ResultCharacterId") REFERENCES "Characters" ("Id") ON DELETE SET NULL
);

CREATE TABLE "SpellSlots" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Level1Id" integer NOT NULL,
    "Level2Id" integer NOT NULL,
    "Level3Id" integer NOT NULL,
    "Level4Id" integer NOT NULL,
    "Level5Id" integer NOT NULL,
    "Level6Id" integer NOT NULL,
    "Level7Id" integer NOT NULL,
    "Level8Id" integer NOT NULL,
    "Level9Id" integer NOT NULL,
    CONSTRAINT "PK_SpellSlots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SpellSlots_Slots_Level1Id" FOREIGN KEY ("Level1Id") REFERENCES "Slots" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SpellSlots_Slots_Level2Id" FOREIGN KEY ("Level2Id") REFERENCES "Slots" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SpellSlots_Slots_Level3Id" FOREIGN KEY ("Level3Id") REFERENCES "Slots" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SpellSlots_Slots_Level4Id" FOREIGN KEY ("Level4Id") REFERENCES "Slots" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SpellSlots_Slots_Level5Id" FOREIGN KEY ("Level5Id") REFERENCES "Slots" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SpellSlots_Slots_Level6Id" FOREIGN KEY ("Level6Id") REFERENCES "Slots" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SpellSlots_Slots_Level7Id" FOREIGN KEY ("Level7Id") REFERENCES "Slots" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SpellSlots_Slots_Level8Id" FOREIGN KEY ("Level8Id") REFERENCES "Slots" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SpellSlots_Slots_Level9Id" FOREIGN KEY ("Level9Id") REFERENCES "Slots" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AbilityScoresSet" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CharacterSheetId" integer NOT NULL,
    "CharacterSheetId1" integer NOT NULL,
    "StrengthId" integer NOT NULL,
    "DexterityId" integer NOT NULL,
    "ConstitutionId" integer NOT NULL,
    "IntelligenceId" integer NOT NULL,
    "WisdomId" integer NOT NULL,
    "CharismaId" integer NOT NULL,
    CONSTRAINT "PK_AbilityScoresSet" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AbilityScoresSet_AbilityScoreValues_CharismaId" FOREIGN KEY ("CharismaId") REFERENCES "AbilityScoreValues" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AbilityScoresSet_AbilityScoreValues_ConstitutionId" FOREIGN KEY ("ConstitutionId") REFERENCES "AbilityScoreValues" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AbilityScoresSet_AbilityScoreValues_DexterityId" FOREIGN KEY ("DexterityId") REFERENCES "AbilityScoreValues" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AbilityScoresSet_AbilityScoreValues_IntelligenceId" FOREIGN KEY ("IntelligenceId") REFERENCES "AbilityScoreValues" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AbilityScoresSet_AbilityScoreValues_StrengthId" FOREIGN KEY ("StrengthId") REFERENCES "AbilityScoreValues" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AbilityScoresSet_AbilityScoreValues_WisdomId" FOREIGN KEY ("WisdomId") REFERENCES "AbilityScoreValues" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AbilityScoresSet_CharacterSheets_CharacterSheetId" FOREIGN KEY ("CharacterSheetId") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AbilityScoresSet_CharacterSheets_CharacterSheetId1" FOREIGN KEY ("CharacterSheetId1") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Appearances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CharacterSheetId" integer NOT NULL,
    "CharacterSheetId1" integer NOT NULL,
    "Size" text NOT NULL,
    "Gender" text NOT NULL,
    "Age" text NOT NULL,
    "Height" text NOT NULL,
    "Weight" text NOT NULL,
    "Skin" text NOT NULL,
    "Eyes" text NOT NULL,
    "Hair" text NOT NULL,
    CONSTRAINT "PK_Appearances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appearances_CharacterSheets_CharacterSheetId" FOREIGN KEY ("CharacterSheetId") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Appearances_CharacterSheets_CharacterSheetId1" FOREIGN KEY ("CharacterSheetId1") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Backstories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CharacterSheetId" integer NOT NULL,
    "CharacterSheetId1" integer NOT NULL,
    "Background" text NOT NULL,
    "Faction" text NOT NULL,
    "Origin" text NOT NULL,
    "SignificantOthers" text NOT NULL,
    "ImportantEvents" text NOT NULL,
    "AlliesAndEnemies" text NOT NULL,
    CONSTRAINT "PK_Backstories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Backstories_CharacterSheets_CharacterSheetId" FOREIGN KEY ("CharacterSheetId") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Backstories_CharacterSheets_CharacterSheetId1" FOREIGN KEY ("CharacterSheetId1") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CharacterInfos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CharacterSheetId" integer NOT NULL,
    "CharacterSheetId1" integer NOT NULL,
    "Name" text NOT NULL,
    "Class" text NOT NULL,
    "Level" integer NOT NULL,
    "Species" text NOT NULL,
    "Subclass" text NOT NULL,
    "Alignment" text NOT NULL,
    "Experience" integer NOT NULL,
    "NextLevelXp" integer NOT NULL,
    "CharacterName" text NOT NULL,
    "ClassAndLevel" text NOT NULL,
    CONSTRAINT "PK_CharacterInfos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CharacterInfos_CharacterSheets_CharacterSheetId" FOREIGN KEY ("CharacterSheetId") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CharacterInfos_CharacterSheets_CharacterSheetId1" FOREIGN KEY ("CharacterSheetId1") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Combats" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CharacterSheetId" integer NOT NULL,
    "CharacterSheetId1" integer NOT NULL,
    "ArmorClass" integer NOT NULL,
    "Initiative" integer NOT NULL,
    "Speed" text NOT NULL,
    "ProficiencyBonus" integer NOT NULL,
    "Inspiration" boolean NOT NULL,
    CONSTRAINT "PK_Combats" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Combats_CharacterSheets_CharacterSheetId" FOREIGN KEY ("CharacterSheetId") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Combats_CharacterSheets_CharacterSheetId1" FOREIGN KEY ("CharacterSheetId1") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Equipments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CharacterSheetId" integer NOT NULL,
    "CharacterSheetId1" integer NOT NULL,
    CONSTRAINT "PK_Equipments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Equipments_CharacterSheets_CharacterSheetId" FOREIGN KEY ("CharacterSheetId") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Equipments_CharacterSheets_CharacterSheetId1" FOREIGN KEY ("CharacterSheetId1") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "FeaturesAndTraits" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CharacterSheetId" integer NOT NULL,
    "Name" text NOT NULL,
    "Source" text NOT NULL,
    "Description" text NOT NULL,
    "Uses" text NOT NULL,
    "Action" text NOT NULL,
    CONSTRAINT "PK_FeaturesAndTraits" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FeaturesAndTraits_CharacterSheets_CharacterSheetId" FOREIGN KEY ("CharacterSheetId") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Personas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CharacterSheetId" integer NOT NULL,
    "CharacterSheetId1" integer NOT NULL,
    "PersonalityTraits" text NOT NULL,
    "Ideals" text NOT NULL,
    "Bonds" text NOT NULL,
    "Flaws" text NOT NULL,
    CONSTRAINT "PK_Personas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Personas_CharacterSheets_CharacterSheetId" FOREIGN KEY ("CharacterSheetId") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Personas_CharacterSheets_CharacterSheetId1" FOREIGN KEY ("CharacterSheetId1") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Proficiencies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CharacterSheetId" integer NOT NULL,
    "CharacterSheetId1" integer NOT NULL,
    "Armor" text[] NOT NULL,
    "Weapons" text[] NOT NULL,
    "Tools" text[] NOT NULL,
    "Languages" text[] NOT NULL,
    CONSTRAINT "PK_Proficiencies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Proficiencies_CharacterSheets_CharacterSheetId" FOREIGN KEY ("CharacterSheetId") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Proficiencies_CharacterSheets_CharacterSheetId1" FOREIGN KEY ("CharacterSheetId1") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SavingThrowsSet" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CharacterSheetId" integer NOT NULL,
    "CharacterSheetId1" integer NOT NULL,
    "StrengthSaveId" integer NOT NULL,
    "DexteritySaveId" integer NOT NULL,
    "ConstitutionSaveId" integer NOT NULL,
    "IntelligenceSaveId" integer NOT NULL,
    "WisdomSaveId" integer NOT NULL,
    "CharismaSaveId" integer NOT NULL,
    CONSTRAINT "PK_SavingThrowsSet" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SavingThrowsSet_CharacterSheets_CharacterSheetId" FOREIGN KEY ("CharacterSheetId") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SavingThrowsSet_CharacterSheets_CharacterSheetId1" FOREIGN KEY ("CharacterSheetId1") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SavingThrowsSet_SavingThrowValues_CharismaSaveId" FOREIGN KEY ("CharismaSaveId") REFERENCES "SavingThrowValues" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SavingThrowsSet_SavingThrowValues_ConstitutionSaveId" FOREIGN KEY ("ConstitutionSaveId") REFERENCES "SavingThrowValues" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SavingThrowsSet_SavingThrowValues_DexteritySaveId" FOREIGN KEY ("DexteritySaveId") REFERENCES "SavingThrowValues" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SavingThrowsSet_SavingThrowValues_IntelligenceSaveId" FOREIGN KEY ("IntelligenceSaveId") REFERENCES "SavingThrowValues" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SavingThrowsSet_SavingThrowValues_StrengthSaveId" FOREIGN KEY ("StrengthSaveId") REFERENCES "SavingThrowValues" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SavingThrowsSet_SavingThrowValues_WisdomSaveId" FOREIGN KEY ("WisdomSaveId") REFERENCES "SavingThrowValues" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Skills" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CharacterSheetId" integer NOT NULL,
    "Name" text NOT NULL,
    "Ability" text NOT NULL,
    "Modifier" integer NOT NULL,
    "Proficient" boolean NOT NULL,
    "Expertise" boolean NOT NULL,
    CONSTRAINT "PK_Skills" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Skills_CharacterSheets_CharacterSheetId" FOREIGN KEY ("CharacterSheetId") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SectionResults" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SectionName" text NOT NULL,
    "IsSuccessful" boolean NOT NULL,
    "ErrorMessage" text,
    "ProcessedAt" timestamp with time zone NOT NULL,
    "ExtractionJobId" integer NOT NULL,
    CONSTRAINT "PK_SectionResults" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SectionResults_ExtractionJobs_ExtractionJobId" FOREIGN KEY ("ExtractionJobId") REFERENCES "ExtractionJobs" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Spellcastings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CharacterSheetId" integer NOT NULL,
    "CharacterSheetId1" integer NOT NULL,
    "Class" text NOT NULL,
    "Ability" text NOT NULL,
    "SaveDC" integer NOT NULL,
    "AttackBonus" integer NOT NULL,
    "SpellSlotsId" integer NOT NULL,
    CONSTRAINT "PK_Spellcastings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Spellcastings_CharacterSheets_CharacterSheetId" FOREIGN KEY ("CharacterSheetId") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Spellcastings_CharacterSheets_CharacterSheetId1" FOREIGN KEY ("CharacterSheetId1") REFERENCES "CharacterSheets" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Spellcastings_SpellSlots_SpellSlotsId" FOREIGN KEY ("SpellSlotsId") REFERENCES "SpellSlots" ("Id") ON DELETE CASCADE
);

CREATE TABLE "DeathSaves" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CombatId" integer NOT NULL,
    "CombatId1" integer NOT NULL,
    "Successes" integer NOT NULL,
    "Failures" integer NOT NULL,
    CONSTRAINT "PK_DeathSaves" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DeathSaves_Combats_CombatId" FOREIGN KEY ("CombatId") REFERENCES "Combats" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DeathSaves_Combats_CombatId1" FOREIGN KEY ("CombatId1") REFERENCES "Combats" ("Id") ON DELETE CASCADE
);

CREATE TABLE "HitDices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CombatId" integer NOT NULL,
    "CombatId1" integer NOT NULL,
    "Total" text NOT NULL,
    "Current" text NOT NULL,
    CONSTRAINT "PK_HitDices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HitDices_Combats_CombatId" FOREIGN KEY ("CombatId") REFERENCES "Combats" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_HitDices_Combats_CombatId1" FOREIGN KEY ("CombatId1") REFERENCES "Combats" ("Id") ON DELETE CASCADE
);

CREATE TABLE "HitPoints" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CombatId" integer NOT NULL,
    "CombatId1" integer NOT NULL,
    "Max" integer NOT NULL,
    "Current" integer NOT NULL,
    "Temporary" integer NOT NULL,
    CONSTRAINT "PK_HitPoints" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HitPoints_Combats_CombatId" FOREIGN KEY ("CombatId") REFERENCES "Combats" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_HitPoints_Combats_CombatId1" FOREIGN KEY ("CombatId1") REFERENCES "Combats" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PassiveScores" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CombatId" integer NOT NULL,
    "CombatId1" integer NOT NULL,
    "Perception" integer NOT NULL,
    "Insight" integer NOT NULL,
    "Investigation" integer NOT NULL,
    CONSTRAINT "PK_PassiveScores" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PassiveScores_Combats_CombatId" FOREIGN KEY ("CombatId") REFERENCES "Combats" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PassiveScores_Combats_CombatId1" FOREIGN KEY ("CombatId1") REFERENCES "Combats" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CarryingCapacities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EquipmentId" integer NOT NULL,
    "EquipmentId1" integer NOT NULL,
    "WeightCarried" real NOT NULL,
    "Encumbered" real NOT NULL,
    "PushDragLift" real NOT NULL,
    CONSTRAINT "PK_CarryingCapacities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CarryingCapacities_Equipments_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CarryingCapacities_Equipments_EquipmentId1" FOREIGN KEY ("EquipmentId1") REFERENCES "Equipments" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Currencies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EquipmentId" integer NOT NULL,
    "EquipmentId1" integer NOT NULL,
    "Cp" integer NOT NULL,
    "Sp" integer NOT NULL,
    "Ep" integer NOT NULL,
    "Gp" integer NOT NULL,
    "Pp" integer NOT NULL,
    CONSTRAINT "PK_Currencies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Currencies_Equipments_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Currencies_Equipments_EquipmentId1" FOREIGN KEY ("EquipmentId1") REFERENCES "Equipments" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Items" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EquipmentId" integer NOT NULL,
    "Name" text NOT NULL,
    "Quantity" integer NOT NULL,
    "Weight" real NOT NULL,
    CONSTRAINT "PK_Items" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Items_Equipments_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipments" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Spells" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SpellcastingId" integer NOT NULL,
    "SpellcastingId1" integer NOT NULL,
    "SpellType" text NOT NULL,
    "Name" text NOT NULL,
    "Level" integer NOT NULL,
    "Source" text NOT NULL,
    "CastingTime" text NOT NULL,
    "Range" text NOT NULL,
    "Components" text NOT NULL,
    "Duration" text NOT NULL,
    "Description" text NOT NULL,
    "AttackId" integer NOT NULL,
    "SaveId" integer NOT NULL,
    CONSTRAINT "PK_Spells" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Spells_SpellAttacks_AttackId" FOREIGN KEY ("AttackId") REFERENCES "SpellAttacks" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Spells_SpellSaves_SaveId" FOREIGN KEY ("SaveId") REFERENCES "SpellSaves" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Spells_Spellcastings_SpellcastingId" FOREIGN KEY ("SpellcastingId") REFERENCES "Spellcastings" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Spells_Spellcastings_SpellcastingId1" FOREIGN KEY ("SpellcastingId1") REFERENCES "Spellcastings" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_AbilityScoresSet_CharacterSheetId" ON "AbilityScoresSet" ("CharacterSheetId");

CREATE INDEX "IX_AbilityScoresSet_CharacterSheetId1" ON "AbilityScoresSet" ("CharacterSheetId1");

CREATE INDEX "IX_AbilityScoresSet_CharismaId" ON "AbilityScoresSet" ("CharismaId");

CREATE INDEX "IX_AbilityScoresSet_ConstitutionId" ON "AbilityScoresSet" ("ConstitutionId");

CREATE INDEX "IX_AbilityScoresSet_DexterityId" ON "AbilityScoresSet" ("DexterityId");

CREATE INDEX "IX_AbilityScoresSet_IntelligenceId" ON "AbilityScoresSet" ("IntelligenceId");

CREATE INDEX "IX_AbilityScoresSet_StrengthId" ON "AbilityScoresSet" ("StrengthId");

CREATE INDEX "IX_AbilityScoresSet_WisdomId" ON "AbilityScoresSet" ("WisdomId");

CREATE UNIQUE INDEX "IX_Appearances_CharacterSheetId" ON "Appearances" ("CharacterSheetId");

CREATE INDEX "IX_Appearances_CharacterSheetId1" ON "Appearances" ("CharacterSheetId1");

CREATE UNIQUE INDEX "IX_Backstories_CharacterSheetId" ON "Backstories" ("CharacterSheetId");

CREATE INDEX "IX_Backstories_CharacterSheetId1" ON "Backstories" ("CharacterSheetId1");

CREATE UNIQUE INDEX "IX_CarryingCapacities_EquipmentId" ON "CarryingCapacities" ("EquipmentId");

CREATE INDEX "IX_CarryingCapacities_EquipmentId1" ON "CarryingCapacities" ("EquipmentId1");

CREATE UNIQUE INDEX "IX_CharacterInfos_CharacterSheetId" ON "CharacterInfos" ("CharacterSheetId");

CREATE INDEX "IX_CharacterInfos_CharacterSheetId1" ON "CharacterInfos" ("CharacterSheetId1");

CREATE UNIQUE INDEX "IX_CharacterSheets_CharacterId" ON "CharacterSheets" ("CharacterId");

CREATE INDEX "IX_CharacterSheets_CharacterId1" ON "CharacterSheets" ("CharacterId1");

CREATE UNIQUE INDEX "IX_Combats_CharacterSheetId" ON "Combats" ("CharacterSheetId");

CREATE INDEX "IX_Combats_CharacterSheetId1" ON "Combats" ("CharacterSheetId1");

CREATE UNIQUE INDEX "IX_Currencies_EquipmentId" ON "Currencies" ("EquipmentId");

CREATE INDEX "IX_Currencies_EquipmentId1" ON "Currencies" ("EquipmentId1");

CREATE UNIQUE INDEX "IX_DeathSaves_CombatId" ON "DeathSaves" ("CombatId");

CREATE INDEX "IX_DeathSaves_CombatId1" ON "DeathSaves" ("CombatId1");

CREATE UNIQUE INDEX "IX_Equipments_CharacterSheetId" ON "Equipments" ("CharacterSheetId");

CREATE INDEX "IX_Equipments_CharacterSheetId1" ON "Equipments" ("CharacterSheetId1");

CREATE UNIQUE INDEX "IX_ExtractionJobs_JobToken" ON "ExtractionJobs" ("JobToken");

CREATE INDEX "IX_ExtractionJobs_ResultCharacterId" ON "ExtractionJobs" ("ResultCharacterId");

CREATE INDEX "IX_FeaturesAndTraits_CharacterSheetId" ON "FeaturesAndTraits" ("CharacterSheetId");

CREATE UNIQUE INDEX "IX_HitDices_CombatId" ON "HitDices" ("CombatId");

CREATE INDEX "IX_HitDices_CombatId1" ON "HitDices" ("CombatId1");

CREATE UNIQUE INDEX "IX_HitPoints_CombatId" ON "HitPoints" ("CombatId");

CREATE INDEX "IX_HitPoints_CombatId1" ON "HitPoints" ("CombatId1");

CREATE INDEX "IX_Items_EquipmentId" ON "Items" ("EquipmentId");

CREATE UNIQUE INDEX "IX_PassiveScores_CombatId" ON "PassiveScores" ("CombatId");

CREATE INDEX "IX_PassiveScores_CombatId1" ON "PassiveScores" ("CombatId1");

CREATE UNIQUE INDEX "IX_Personas_CharacterSheetId" ON "Personas" ("CharacterSheetId");

CREATE INDEX "IX_Personas_CharacterSheetId1" ON "Personas" ("CharacterSheetId1");

CREATE UNIQUE INDEX "IX_Proficiencies_CharacterSheetId" ON "Proficiencies" ("CharacterSheetId");

CREATE INDEX "IX_Proficiencies_CharacterSheetId1" ON "Proficiencies" ("CharacterSheetId1");

CREATE UNIQUE INDEX "IX_SavingThrowsSet_CharacterSheetId" ON "SavingThrowsSet" ("CharacterSheetId");

CREATE INDEX "IX_SavingThrowsSet_CharacterSheetId1" ON "SavingThrowsSet" ("CharacterSheetId1");

CREATE INDEX "IX_SavingThrowsSet_CharismaSaveId" ON "SavingThrowsSet" ("CharismaSaveId");

CREATE INDEX "IX_SavingThrowsSet_ConstitutionSaveId" ON "SavingThrowsSet" ("ConstitutionSaveId");

CREATE INDEX "IX_SavingThrowsSet_DexteritySaveId" ON "SavingThrowsSet" ("DexteritySaveId");

CREATE INDEX "IX_SavingThrowsSet_IntelligenceSaveId" ON "SavingThrowsSet" ("IntelligenceSaveId");

CREATE INDEX "IX_SavingThrowsSet_StrengthSaveId" ON "SavingThrowsSet" ("StrengthSaveId");

CREATE INDEX "IX_SavingThrowsSet_WisdomSaveId" ON "SavingThrowsSet" ("WisdomSaveId");

CREATE INDEX "IX_SectionResults_ExtractionJobId" ON "SectionResults" ("ExtractionJobId");

CREATE INDEX "IX_Skills_CharacterSheetId" ON "Skills" ("CharacterSheetId");

CREATE UNIQUE INDEX "IX_Spellcastings_CharacterSheetId" ON "Spellcastings" ("CharacterSheetId");

CREATE INDEX "IX_Spellcastings_CharacterSheetId1" ON "Spellcastings" ("CharacterSheetId1");

CREATE INDEX "IX_Spellcastings_SpellSlotsId" ON "Spellcastings" ("SpellSlotsId");

CREATE INDEX "IX_Spells_AttackId" ON "Spells" ("AttackId");

CREATE INDEX "IX_Spells_SaveId" ON "Spells" ("SaveId");

CREATE INDEX "IX_Spells_SpellcastingId" ON "Spells" ("SpellcastingId");

CREATE INDEX "IX_Spells_SpellcastingId1" ON "Spells" ("SpellcastingId1");

CREATE INDEX "IX_SpellSlots_Level1Id" ON "SpellSlots" ("Level1Id");

CREATE INDEX "IX_SpellSlots_Level2Id" ON "SpellSlots" ("Level2Id");

CREATE INDEX "IX_SpellSlots_Level3Id" ON "SpellSlots" ("Level3Id");

CREATE INDEX "IX_SpellSlots_Level4Id" ON "SpellSlots" ("Level4Id");

CREATE INDEX "IX_SpellSlots_Level5Id" ON "SpellSlots" ("Level5Id");

CREATE INDEX "IX_SpellSlots_Level6Id" ON "SpellSlots" ("Level6Id");

CREATE INDEX "IX_SpellSlots_Level7Id" ON "SpellSlots" ("Level7Id");

CREATE INDEX "IX_SpellSlots_Level8Id" ON "SpellSlots" ("Level8Id");

CREATE INDEX "IX_SpellSlots_Level9Id" ON "SpellSlots" ("Level9Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250806105941_CompleteCharacterSheetMapping', '9.0.1');

ALTER TABLE "AbilityScoresSet" DROP CONSTRAINT "FK_AbilityScoresSet_CharacterSheets_CharacterSheetId1";

ALTER TABLE "Appearances" DROP CONSTRAINT "FK_Appearances_CharacterSheets_CharacterSheetId1";

ALTER TABLE "Backstories" DROP CONSTRAINT "FK_Backstories_CharacterSheets_CharacterSheetId1";

ALTER TABLE "CharacterInfos" DROP CONSTRAINT "FK_CharacterInfos_CharacterSheets_CharacterSheetId1";

ALTER TABLE "Combats" DROP CONSTRAINT "FK_Combats_CharacterSheets_CharacterSheetId1";

ALTER TABLE "Equipments" DROP CONSTRAINT "FK_Equipments_CharacterSheets_CharacterSheetId1";

ALTER TABLE "Personas" DROP CONSTRAINT "FK_Personas_CharacterSheets_CharacterSheetId1";

ALTER TABLE "Proficiencies" DROP CONSTRAINT "FK_Proficiencies_CharacterSheets_CharacterSheetId1";

ALTER TABLE "SavingThrowsSet" DROP CONSTRAINT "FK_SavingThrowsSet_CharacterSheets_CharacterSheetId1";

ALTER TABLE "Spellcastings" DROP CONSTRAINT "FK_Spellcastings_CharacterSheets_CharacterSheetId1";

DROP INDEX "IX_Spellcastings_CharacterSheetId1";

DROP INDEX "IX_SavingThrowsSet_CharacterSheetId1";

DROP INDEX "IX_Proficiencies_CharacterSheetId1";

DROP INDEX "IX_Personas_CharacterSheetId1";

DROP INDEX "IX_Equipments_CharacterSheetId1";

DROP INDEX "IX_Combats_CharacterSheetId1";

DROP INDEX "IX_CharacterInfos_CharacterSheetId1";

DROP INDEX "IX_Backstories_CharacterSheetId1";

DROP INDEX "IX_Appearances_CharacterSheetId1";

DROP INDEX "IX_AbilityScoresSet_CharacterSheetId1";

ALTER TABLE "Spellcastings" DROP COLUMN "CharacterSheetId1";

ALTER TABLE "SavingThrowsSet" DROP COLUMN "CharacterSheetId1";

ALTER TABLE "Proficiencies" DROP COLUMN "CharacterSheetId1";

ALTER TABLE "Personas" DROP COLUMN "CharacterSheetId1";

ALTER TABLE "Equipments" DROP COLUMN "CharacterSheetId1";

ALTER TABLE "Combats" DROP COLUMN "CharacterSheetId1";

ALTER TABLE "CharacterInfos" DROP COLUMN "CharacterSheetId1";

ALTER TABLE "Backstories" DROP COLUMN "CharacterSheetId1";

ALTER TABLE "Appearances" DROP COLUMN "CharacterSheetId1";

ALTER TABLE "AbilityScoresSet" DROP COLUMN "CharacterSheetId1";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250806141317_FixedModelRelationships', '9.0.1');

ALTER TABLE "CarryingCapacities" DROP CONSTRAINT "FK_CarryingCapacities_Equipments_EquipmentId1";

ALTER TABLE "CharacterSheets" DROP CONSTRAINT "FK_CharacterSheets_Characters_CharacterId1";

ALTER TABLE "Currencies" DROP CONSTRAINT "FK_Currencies_Equipments_EquipmentId1";

ALTER TABLE "DeathSaves" DROP CONSTRAINT "FK_DeathSaves_Combats_CombatId1";

ALTER TABLE "HitDices" DROP CONSTRAINT "FK_HitDices_Combats_CombatId1";

ALTER TABLE "HitPoints" DROP CONSTRAINT "FK_HitPoints_Combats_CombatId1";

ALTER TABLE "PassiveScores" DROP CONSTRAINT "FK_PassiveScores_Combats_CombatId1";

DROP INDEX "IX_PassiveScores_CombatId1";

DROP INDEX "IX_HitPoints_CombatId1";

DROP INDEX "IX_HitDices_CombatId1";

DROP INDEX "IX_DeathSaves_CombatId1";

DROP INDEX "IX_Currencies_EquipmentId1";

DROP INDEX "IX_CharacterSheets_CharacterId1";

DROP INDEX "IX_CarryingCapacities_EquipmentId1";

ALTER TABLE "PassiveScores" DROP COLUMN "CombatId1";

ALTER TABLE "HitPoints" DROP COLUMN "CombatId1";

ALTER TABLE "HitDices" DROP COLUMN "CombatId1";

ALTER TABLE "DeathSaves" DROP COLUMN "CombatId1";

ALTER TABLE "Currencies" DROP COLUMN "EquipmentId1";

ALTER TABLE "CharacterSheets" DROP COLUMN "CharacterId1";

ALTER TABLE "Characters" DROP COLUMN "CharacterSheetId";

ALTER TABLE "CarryingCapacities" DROP COLUMN "EquipmentId1";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250806155253_RemoveCharacterSheetIdFromCharacter', '9.0.1');

COMMIT;

